application: maloquim
version: epsilon
runtime: go
api_version: go1

handlers:

# Static content

- url: /app
  static_dir: extension/app

- url: /media
  static_dir: extension/media

- url: /theme
  static_dir: extension/theme

# Just while I'm debugging the application
- url: /index.html
  static_files: index.html
  upload: index.html

# The rest is handled by the application

- url: /.*
  script: _go_app
